//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderDataLayer.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class bookmytableEntities : DbContext
    {
        public bookmytableEntities()
            : base("name=bookmytableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<AddTableBookAndMenuOrder_Result> AddTableBookAndMenuOrder(Nullable<int> p_intHotelId, Nullable<int> p_intDishID, Nullable<decimal> p_dcmlTotalAmt, string p_vchApprovalName, string p_vchCustomerName, string p_vchPhoneNumber, string p_vchLastname, string p_vchEmailID, string p_vchCity, string p_vchCountry, string p_vchAddress)
        {
            var p_intHotelIdParameter = p_intHotelId.HasValue ?
                new ObjectParameter("p_intHotelId", p_intHotelId) :
                new ObjectParameter("p_intHotelId", typeof(int));
    
            var p_intDishIDParameter = p_intDishID.HasValue ?
                new ObjectParameter("P_intDishID", p_intDishID) :
                new ObjectParameter("P_intDishID", typeof(int));
    
            var p_dcmlTotalAmtParameter = p_dcmlTotalAmt.HasValue ?
                new ObjectParameter("P_dcmlTotalAmt", p_dcmlTotalAmt) :
                new ObjectParameter("P_dcmlTotalAmt", typeof(decimal));
    
            var p_vchApprovalNameParameter = p_vchApprovalName != null ?
                new ObjectParameter("p_vchApprovalName", p_vchApprovalName) :
                new ObjectParameter("p_vchApprovalName", typeof(string));
    
            var p_vchCustomerNameParameter = p_vchCustomerName != null ?
                new ObjectParameter("p_vchCustomerName", p_vchCustomerName) :
                new ObjectParameter("p_vchCustomerName", typeof(string));
    
            var p_vchPhoneNumberParameter = p_vchPhoneNumber != null ?
                new ObjectParameter("p_vchPhoneNumber", p_vchPhoneNumber) :
                new ObjectParameter("p_vchPhoneNumber", typeof(string));
    
            var p_vchLastnameParameter = p_vchLastname != null ?
                new ObjectParameter("p_vchLastname", p_vchLastname) :
                new ObjectParameter("p_vchLastname", typeof(string));
    
            var p_vchEmailIDParameter = p_vchEmailID != null ?
                new ObjectParameter("p_vchEmailID", p_vchEmailID) :
                new ObjectParameter("p_vchEmailID", typeof(string));
    
            var p_vchCityParameter = p_vchCity != null ?
                new ObjectParameter("p_vchCity", p_vchCity) :
                new ObjectParameter("p_vchCity", typeof(string));
    
            var p_vchCountryParameter = p_vchCountry != null ?
                new ObjectParameter("p_vchCountry", p_vchCountry) :
                new ObjectParameter("p_vchCountry", typeof(string));
    
            var p_vchAddressParameter = p_vchAddress != null ?
                new ObjectParameter("p_vchAddress", p_vchAddress) :
                new ObjectParameter("p_vchAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddTableBookAndMenuOrder_Result>("AddTableBookAndMenuOrder", p_intHotelIdParameter, p_intDishIDParameter, p_dcmlTotalAmtParameter, p_vchApprovalNameParameter, p_vchCustomerNameParameter, p_vchPhoneNumberParameter, p_vchLastnameParameter, p_vchEmailIDParameter, p_vchCityParameter, p_vchCountryParameter, p_vchAddressParameter);
        }
    
        public virtual ObjectResult<Sp_GetHotelMenuDetails_Result> Sp_GetHotelMenuDetails(Nullable<int> hotelId)
        {
            var hotelIdParameter = hotelId.HasValue ?
                new ObjectParameter("HotelId", hotelId) :
                new ObjectParameter("HotelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetHotelMenuDetails_Result>("Sp_GetHotelMenuDetails", hotelIdParameter);
        }
    
        public virtual ObjectResult<Sp_GetRestaurantsDetails_Result> Sp_GetRestaurantsDetails(Nullable<int> vch_IsActive)
        {
            var vch_IsActiveParameter = vch_IsActive.HasValue ?
                new ObjectParameter("Vch_IsActive", vch_IsActive) :
                new ObjectParameter("Vch_IsActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetRestaurantsDetails_Result>("Sp_GetRestaurantsDetails", vch_IsActiveParameter);
        }
    
        public virtual ObjectResult<Sp_GetRestaurantsTablesDetails_Result> Sp_GetRestaurantsTablesDetails(Nullable<int> hotelId)
        {
            var hotelIdParameter = hotelId.HasValue ?
                new ObjectParameter("HotelId", hotelId) :
                new ObjectParameter("HotelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetRestaurantsTablesDetails_Result>("Sp_GetRestaurantsTablesDetails", hotelIdParameter);
        }
    }
}
