//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderingWebService.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalStatusAttribute
    {
        public int Id { get; set; }
        public string ApprovalDescription { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public byte[] ts { get; set; }
    }
}
