//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderingWebService.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bookmytableEntities : DbContext
    {
        public bookmytableEntities()
            : base("name=bookmytableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApprovalStatusAttribute> ApprovalStatusAttributes { get; set; }
        public virtual DbSet<CustomerTable> CustomerTables { get; set; }
        public virtual DbSet<EmploteeAttributeMaster> EmploteeAttributeMasters { get; set; }
        public virtual DbSet<HotelEmployeeDetail> HotelEmployeeDetails { get; set; }
        public virtual DbSet<HotelMenuTable> HotelMenuTables { get; set; }
        public virtual DbSet<HotelTableAndOrderBooking> HotelTableAndOrderBookings { get; set; }
        public virtual DbSet<HotelTableDetail> HotelTableDetails { get; set; }
        public virtual DbSet<OrderPaymentDetail> OrderPaymentDetails { get; set; }
        public virtual DbSet<PaymentAttributeMaster> PaymentAttributeMasters { get; set; }
        public virtual DbSet<RestaurantsDetail> RestaurantsDetails { get; set; }
        public virtual DbSet<TableCapacityAttribute> TableCapacityAttributes { get; set; }
        public virtual DbSet<TemplateContent> TemplateContents { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersPassword> UsersPasswords { get; set; }
        public virtual DbSet<UserBase> UserBases { get; set; }
        public virtual DbSet<OrderMenuEntity> OrderMenuEntities { get; set; }
    
        public virtual ObjectResult<string> AddSignUpUserDetails(string userName, string firstname, string lastname, string emailID, string mobileNumber, string gender, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("Firstname", firstname) :
                new ObjectParameter("Firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("Lastname", lastname) :
                new ObjectParameter("Lastname", typeof(string));
    
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var mobileNumberParameter = mobileNumber != null ?
                new ObjectParameter("MobileNumber", mobileNumber) :
                new ObjectParameter("MobileNumber", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AddSignUpUserDetails", userNameParameter, firstnameParameter, lastnameParameter, emailIDParameter, mobileNumberParameter, genderParameter, passwordParameter);
        }
    
        public virtual ObjectResult<AddTableBookAndMenuOrder_Result> AddTableBookAndMenuOrder(Nullable<int> p_intHotelId, Nullable<int> p_intDishID, Nullable<decimal> p_dcmlTotalAmt, string p_vchApprovalName, string p_vchCustomerName, string p_vchPhoneNumber, string p_vchEmailID, string p_vchCity, string p_vchCountry, string p_vchAddress)
        {
            var p_intHotelIdParameter = p_intHotelId.HasValue ?
                new ObjectParameter("p_intHotelId", p_intHotelId) :
                new ObjectParameter("p_intHotelId", typeof(int));
    
            var p_intDishIDParameter = p_intDishID.HasValue ?
                new ObjectParameter("P_intDishID", p_intDishID) :
                new ObjectParameter("P_intDishID", typeof(int));
    
            var p_dcmlTotalAmtParameter = p_dcmlTotalAmt.HasValue ?
                new ObjectParameter("P_dcmlTotalAmt", p_dcmlTotalAmt) :
                new ObjectParameter("P_dcmlTotalAmt", typeof(decimal));
    
            var p_vchApprovalNameParameter = p_vchApprovalName != null ?
                new ObjectParameter("p_vchApprovalName", p_vchApprovalName) :
                new ObjectParameter("p_vchApprovalName", typeof(string));
    
            var p_vchCustomerNameParameter = p_vchCustomerName != null ?
                new ObjectParameter("p_vchCustomerName", p_vchCustomerName) :
                new ObjectParameter("p_vchCustomerName", typeof(string));
    
            var p_vchPhoneNumberParameter = p_vchPhoneNumber != null ?
                new ObjectParameter("p_vchPhoneNumber", p_vchPhoneNumber) :
                new ObjectParameter("p_vchPhoneNumber", typeof(string));
    
            var p_vchEmailIDParameter = p_vchEmailID != null ?
                new ObjectParameter("p_vchEmailID", p_vchEmailID) :
                new ObjectParameter("p_vchEmailID", typeof(string));
    
            var p_vchCityParameter = p_vchCity != null ?
                new ObjectParameter("p_vchCity", p_vchCity) :
                new ObjectParameter("p_vchCity", typeof(string));
    
            var p_vchCountryParameter = p_vchCountry != null ?
                new ObjectParameter("p_vchCountry", p_vchCountry) :
                new ObjectParameter("p_vchCountry", typeof(string));
    
            var p_vchAddressParameter = p_vchAddress != null ?
                new ObjectParameter("p_vchAddress", p_vchAddress) :
                new ObjectParameter("p_vchAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddTableBookAndMenuOrder_Result>("AddTableBookAndMenuOrder", p_intHotelIdParameter, p_intDishIDParameter, p_dcmlTotalAmtParameter, p_vchApprovalNameParameter, p_vchCustomerNameParameter, p_vchPhoneNumberParameter, p_vchEmailIDParameter, p_vchCityParameter, p_vchCountryParameter, p_vchAddressParameter);
        }
    
        public virtual ObjectResult<SavehtmlTemplateToDb_Result> SavehtmlTemplateToDb(string htmlText, string subMitedUser)
        {
            var htmlTextParameter = htmlText != null ?
                new ObjectParameter("HtmlText", htmlText) :
                new ObjectParameter("HtmlText", typeof(string));
    
            var subMitedUserParameter = subMitedUser != null ?
                new ObjectParameter("SubMitedUser", subMitedUser) :
                new ObjectParameter("SubMitedUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SavehtmlTemplateToDb_Result>("SavehtmlTemplateToDb", htmlTextParameter, subMitedUserParameter);
        }
    
        public virtual ObjectResult<Sp_GetHotelMenuDetails_Result> Sp_GetHotelMenuDetails(Nullable<int> hotelId)
        {
            var hotelIdParameter = hotelId.HasValue ?
                new ObjectParameter("HotelId", hotelId) :
                new ObjectParameter("HotelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetHotelMenuDetails_Result>("Sp_GetHotelMenuDetails", hotelIdParameter);
        }
    
        public virtual ObjectResult<Sp_GetRestaurantsDetails_Result> Sp_GetRestaurantsDetails(Nullable<int> vch_IsActive)
        {
            var vch_IsActiveParameter = vch_IsActive.HasValue ?
                new ObjectParameter("Vch_IsActive", vch_IsActive) :
                new ObjectParameter("Vch_IsActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetRestaurantsDetails_Result>("Sp_GetRestaurantsDetails", vch_IsActiveParameter);
        }
    
        public virtual ObjectResult<Sp_GetRestaurantsTablesDetails_Result> Sp_GetRestaurantsTablesDetails(Nullable<int> hotelId)
        {
            var hotelIdParameter = hotelId.HasValue ?
                new ObjectParameter("HotelId", hotelId) :
                new ObjectParameter("HotelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetRestaurantsTablesDetails_Result>("Sp_GetRestaurantsTablesDetails", hotelIdParameter);
        }
    
        public virtual ObjectResult<Sp_GetUserDetailsDqata_Result> Sp_GetUserDetailsDqata(Nullable<System.DateTime> formDt)
        {
            var formDtParameter = formDt.HasValue ?
                new ObjectParameter("formDt", formDt) :
                new ObjectParameter("formDt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetUserDetailsDqata_Result>("Sp_GetUserDetailsDqata", formDtParameter);
        }
    
        public virtual ObjectResult<Sp_GetUserAndUserRoleDetails_Result> Sp_GetUserAndUserRoleDetails(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetUserAndUserRoleDetails_Result>("Sp_GetUserAndUserRoleDetails", userNameParameter, passwordParameter);
        }
    
        public virtual int AddOrderMenuDetails(Nullable<int> p_intHotelId, Nullable<int> p_intDishID, Nullable<decimal> p_dcmlTotalAmt, Nullable<int> p_OrderId, Nullable<int> p_intQuantity, string p_vchDishName)
        {
            var p_intHotelIdParameter = p_intHotelId.HasValue ?
                new ObjectParameter("p_intHotelId", p_intHotelId) :
                new ObjectParameter("p_intHotelId", typeof(int));
    
            var p_intDishIDParameter = p_intDishID.HasValue ?
                new ObjectParameter("P_intDishID", p_intDishID) :
                new ObjectParameter("P_intDishID", typeof(int));
    
            var p_dcmlTotalAmtParameter = p_dcmlTotalAmt.HasValue ?
                new ObjectParameter("P_dcmlTotalAmt", p_dcmlTotalAmt) :
                new ObjectParameter("P_dcmlTotalAmt", typeof(decimal));
    
            var p_OrderIdParameter = p_OrderId.HasValue ?
                new ObjectParameter("p_OrderId", p_OrderId) :
                new ObjectParameter("p_OrderId", typeof(int));
    
            var p_intQuantityParameter = p_intQuantity.HasValue ?
                new ObjectParameter("P_intQuantity", p_intQuantity) :
                new ObjectParameter("P_intQuantity", typeof(int));
    
            var p_vchDishNameParameter = p_vchDishName != null ?
                new ObjectParameter("p_vchDishName", p_vchDishName) :
                new ObjectParameter("p_vchDishName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddOrderMenuDetails", p_intHotelIdParameter, p_intDishIDParameter, p_dcmlTotalAmtParameter, p_OrderIdParameter, p_intQuantityParameter, p_vchDishNameParameter);
        }
    
        public virtual ObjectResult<Sp_GetOrderDetails_Result> Sp_GetOrderDetails(Nullable<int> orderID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetOrderDetails_Result>("Sp_GetOrderDetails", orderIDParameter);
        }
    
        public virtual ObjectResult<Sp_GetOrderDetailsToEmployee_Result> Sp_GetOrderDetailsToEmployee(Nullable<int> employeeID, Nullable<int> roleID)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetOrderDetailsToEmployee_Result>("Sp_GetOrderDetailsToEmployee", employeeIDParameter, roleIDParameter);
        }
    }
}
