//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderingWebService.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelTableAndOrderBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelTableAndOrderBooking()
        {
            this.OrderMenuEntities = new HashSet<OrderMenuEntity>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> TableId { get; set; }
        public Nullable<int> DishId { get; set; }
        public Nullable<int> IsApproveStatus { get; set; }
        public string ApprovalName { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] ts { get; set; }
    
        public virtual HotelMenuTable HotelMenuTable { get; set; }
        public virtual RestaurantsDetail RestaurantsDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMenuEntity> OrderMenuEntities { get; set; }
    }
}
